Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.21"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "app" do |app|
    app.vm.box = "centos/stream9"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.22"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/stream9"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.23"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

end

